--- 
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata: 
  labels: 
    app: traefik
  name: http-app-1
  namespace: default
spec: 
  hostnames: 
    - whoami
  rules: 
    - 
      backendRefs: 
        - 
          port: 80
          name: whoami
          weight: 3
        - 
          port: 80
          name: nginx
          weight: 1